### ISSUE TITLE
The Fat Controller does not work with mod iconizer.

### ISSUE THREAD

**Issue by madPav3L** [Roktaal/mod-iconizer#2]
Great mod but if I use it The Fat Controller stops working.
At first I was using old version of The Fat Controller 0.3.23 and when I tried to control a train these errors appear. ![the fat controller 0 3 23](https://cloud.githubusercontent.com/assets/18511359/14586177/5f2d3864-0490-11e6-9ad8-52221989ba43.jpg)
The last code 1092 keeps showing every second or so nonstop. Without the mod iconizer there are no problems.
So after some testing I found out that if I activate mod iconizer save the game and then activate The Fat Controller, there are no errors all is working fine but I can see bot icons, the new graphic icon + the old "Trains+" icon.

So I updated to the new version of The Fat Controller 0.4.11 and when I tried to control a train these errors appear and I am not able to control any train again.
![the fat controller 0 4 11 pic 1](https://cloud.githubusercontent.com/assets/18511359/14586226/b2eda168-0491-11e6-81cf-e0f556b63722.jpg)
This 18 code appears after pressing the train control button "c".
![the fat controller 0 4 11 pic 2](https://cloud.githubusercontent.com/assets/18511359/14586231/d331c81e-0491-11e6-827f-77966ea4ff91.jpg)
This 34 core appears after pressing the "X" button to stop controlling a train.

So no matter what I do, I cannot control trains with The Fat Controller while mod iconizer is on.
I don't know what should I do to get it working?
Thanks

EDIT: I have forgot to mention that I tested this with Factorio versions 0.12.29 and 0.12.30

**Comment by Roktaal** [comment]
Fixed in 1.1.0
